### ISSUE TITLE
Empty directory isn't part of file system artifact-source

### ISSUE THREAD

**Issue by cdupuis** [atomist/artifact-source#10]
Then creating a FileSystemArtifactSource, empty directories appear to be missing. Is that a design decision?

**Comment by alankstewart** [comment]
@cdupuis  Can't reproduce this. Only reason why pending failed test added recently failed  was because by default, empty directories are not copied over to the target directory during a Maven build. Added a maven-resources-plugin configuration fixes this.The test successfully loaded an empty directory into an artifact source. Please open again if you still think an issue exists

**Comment by cdupuis** [comment]
```   
   @Test
    public void testEmtpyDir() {
        File folder = new File(System.getProperty("java.io.tmpdir"));
        File testFolder = new File(folder, "test-case");
        File atomistFolder = new File(testFolder, ".atomist");
        atomistFolder.mkdirs();
        
        assertTrue(atomistFolder.exists() && atomistFolder.isDirectory());
        
        ArtifactSource source = new FileSystemArtifactSource(new SimpleFileSystemArtifactSourceIdentifier(testFolder));
        assertTrue(source.findDirectory(".atomist").isDefined());

    }```

With 0.11.4 the above test was failing. Now with latest it is indeed working. So not sure what you fixed, but you fixed it.
